spring:
  application:
    name: mutant
  datasource:
    url: jdbc:h2:mem:mutantdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
