spring:
  application:
    name: mutant
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/h2db/db/mutant;DB_CLOSE_DELAY=-1
    username: mutant
    password:
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
